### ISSUE TITLE
[VOID] 13/08 05:24:00 CMD .sticker[0] from Adithya Pai B 🦦 in ~UwU~ [VOID] 13/08 05:28:53 Command failed: mogrify -bordercolor transparent -border 39x0 /tmp/0.sbaej49lmc.png /bin/sh: 1: mogrify: not found

### ISSUE THREAD

**Issue by adithyapaib** [Synthesized-Infinity/Whatsapp-Botto-Void#10]
[VOID] 13/08 05:24:00 CMD .sticker[0] from Adithya Pai B 🦦 in ~UwU~
[VOID] 13/08 05:28:53 Command failed: mogrify -bordercolor transparent -border 39x0 /tmp/0.sbaej49lmc.png
/bin/sh: 1: mogrify: not found

Also update high vulnerability packages

**Comment by PrajjwalDatir** [comment]
is `https://github.com/DuckyTeam/heroku-buildpack-imagemagick` added to 
your system ( if you are running locally )? /
heroku buildpack ( if you are running it on heroku )?

**Comment by adithyapaib** [comment]
im running locally i didnt add it

**Comment by adithyapaib** [comment]
how to  do 

it ?

**Comment by AlenSaito1** [comment]
Looks like you don't have *ImageMagick* installed 
Install it from [here](https://imagemagick.org/script/download.php) and make sure to add the legacy tools while setting up.
Let me know how it goes.
