### ISSUE TITLE
how do i use third party apis

### ISSUE THREAD

**Issue by bilal-08** [Synthesized-Infinity/Whatsapp-Botto-Void#14]
like this api
> https://api.mfarelsz.xyz/api/magernulis1?text=indeed
>> api ded tho
 it will make image and add indeed as text in generated image
so what i want is

how to i fetch and send this Image/sticker 
and how do i change the text = name property
to user entered argument?

**Comment by AlenSaito1** [comment]
https://github.com/Synthesized-Infinity/Whatsapp-Botto-Void/blob/b0c91a3e9406ed7289d7ce684aeaf28e318ab9b1/src/lib/request.ts#L3-L6

**Comment by satyammayy** [comment]
i don't know how to use this
