### ISSUE TITLE
Command Request `search`

### ISSUE THREAD

**Issue by PrajjwalDatir** [Synthesized-Infinity/Whatsapp-Botto-Void#18]
command `search [query]`
which will fetch the search results using any one of the search engine like google, bing, yahoo, duckduckgo and show page 1 results

Also recommendation to force push everything except first result into `read more` of the WAmessage

**Comment by AlenSaito1** [comment]
@SomnathDas

**Comment by SomnathDas** [comment]
@PrajjwalDatir remind me tomorrow
