### ISSUE TITLE
Command Game Request `chess`

### ISSUE THREAD

**Issue by PrajjwalDatir** [Synthesized-Infinity/Whatsapp-Botto-Void#19]
Chess Game Using WA Messages.
Players will send Chess Notations like e4, e5, Nf3, Qxf5, ...
And Bot will reply with Current board image with relevant caption if necessary.
---

My Approach : 
- `chess @player1 @player2 (self if no second parameter given) ` will start the game.
- Use Chess API : [example](https://github.com/jhlywa/chess.js) to get board details and to run logic under the hood.
- Use board matrix received from Chess API to build an Image of the current board and deliver it as a WA Message
with caption as `@player1 played %move. Now it's @player2's turn.`
- `chess QUIT` will quit the game and the person sending the message will be considered as lost.
- x amount of inactivity will result in player losing i.e. match end
---
For example,
Consider 3 characters
- player1
- player2 
- Bot
And Prefix as &

Refer [this](https://www.ichess.net/blog/chess-notation/) for Chess notations
# Example Chat =>

### bot : 
![image](https://user-images.githubusercontent.com/46681482/122934955-9646bd80-d38d-11eb-8bfb-4b39404d9c19.png)
Game has began between @player1(white) & @player2(black)

### bot : 
![image](https://user-images.githubusercontent.com/46681482/122938884-c17edc00-d390-11eb-84df-6071176351db.png)
@player1 played e4. Now it's @player2's turn.

### bot: 
![image](https://user-images.githubusercontent.com/46681482/122937201-68627880-d38f-11eb-982d-eb22c23885f5.png)
@player2 played e5. Now it's @player1's turn.

### bot : 
![image](https://user-images.githubusercontent.com/46681482/122938294-40bfe000-d390-11eb-8871-efbcdb2927dc.png)
@player1 played Bc4. Now it's @player2's turn.

### bot :
![image](https://user-images.githubusercontent.com/46681482/122938350-4e756580-d390-11eb-9794-4dc5228696cd.png)
@player2 played Nc6 Now it's @player1's turn.

### bot :
![image](https://user-images.githubusercontent.com/46681482/122938524-76fd5f80-d390-11eb-9f10-f72d5188afb9.png)
@player1 played Qf3. Now it's @player2's turn.

### bot :
![image](https://user-images.githubusercontent.com/46681482/122938619-8aa8c600-d390-11eb-8a61-27791a5c8de7.png)
@player2 played Nd4. Now it's @player1's turn.

### bot : 
![image](https://user-images.githubusercontent.com/46681482/122938677-972d1e80-d390-11eb-88e2-1456a3382613.png)
@player1 played replaced f7 pawn with Queen and has threatened the opponent king.
It's a checkmate!!! @player1 has won 🥳 🔥 

--- 
Drop a comment if you have any doubts or need any clarification on my idea.

Further ideas : 
- giving people in-game currency based on Bets of the players which can be passed as an extra optional parameter while starting the game.

**Comment by AlenSaito1** [comment]
@shubham8550

**Comment by SomnathDas** [comment]
Theoretically easy peasy

**Comment by PrajjwalDatir** [comment]
@SomnathDas Enjoy the journey 🚀

**Comment by AlenSaito1** [comment]
Updates here https://github.com/AlenSaito1/chess-node
