### ISSUE TITLE
QR code didn't show up !

### ISSUE THREAD

**Issue by satyammayy** [Synthesized-Infinity/Whatsapp-Botto-Void#23]

**Comment by satyammayy** [comment]
@SomnathDas @PrajjwalDatir @AlenSaito1 @bilal-08

**Comment by PrajjwalDatir** [comment]
- Where are you deploying Heroku or Localhost
- QR code didn't show up or you weren't able to scan the code?

@satyammayy Write a detailed issue.

**Comment by satyammayy** [comment]
it's local host

  QR code didn't show up !  

No QR to scan @PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
Paste here , all the messages/logs you have gotten.
After you run it.

@satyammayy

**Comment by satyammayy** [comment]
root@ghost-Presario-CQ43-Notebook-PC:/home/ghost/try/Whatsapp-Botto-Void# npm start

> whatsapp-botto-void@1.0.0 start
> node dist/void.js

[VOID] 13/04 01:39:05 Starting...
[VOID] 13/04 01:39:11 Loading Commands...
[VOID] 13/04 01:39:15 Loaded: demote from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Admin/Demote.js
[VOID] 13/04 01:39:17 Loaded: promote from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Admin/Promote.js
[VOID] 13/04 01:39:18 Loaded: remove from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Admin/Remove.js
[VOID] 13/04 01:39:19 Loaded: admins from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Admins.js
[VOID] 13/04 01:39:21 Loaded: help from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Help.js
[VOID] 13/04 01:39:22 Loaded: mods from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Mods.js
[VOID] 13/04 01:39:44 Loaded: profile from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Profile.js
[VOID] 13/04 01:39:45 Loaded: xp from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Xp.js
[VOID] 13/04 01:43:06 Loaded: spotify from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/Spotify.js
[VOID] 13/04 01:43:09 Loaded: yta from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/YTAudio.js
[VOID] 13/04 01:43:10 Loaded: ytv from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/YTVideo.js
[VOID] 13/04 01:43:11 Loaded: hi from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Misc/Hi.js
[VOID] 13/04 01:43:12 Loaded: void from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Misc/Void.js
[VOID] 13/04 01:43:13 Loaded: ban from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Mod/Ban.js
[VOID] 13/04 01:43:14 Loaded: eval from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Mod/Eval.js
[VOID] 13/04 01:43:15 Loaded: unban from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Mod/Unban.js
[VOID] 13/04 01:48:13 Loaded: sticker from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Utils/Sticker.js
[VOID] 13/04 01:48:14 Successfully Loaded 17 Commands
[VOID] 13/04 01:48:14 Loaded: void from /home/ghost/try/Whatsapp-Botto-Void/assets/images/void.png
[VOID] 13/04 01:48:15 Successfully Loaded 1 Assets
[VOID] 13/04 01:48:32 Server Started on PORT: 4040
[VOID] 13/04 02:39:35 Connected to Database!
/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97
            throw new Constants_1.BaileysError(`Unexpected error in login`, { response, status: response.status });
                  ^

BaileysError: Unexpected error in login
    at WAClient.authenticate (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40) {
  status: 419,
  context: { response: { status: 419 }, status: 419 }
}

**Comment by satyammayy** [comment]
This is new it didn't show up before

Before it shows 

Connected to database


/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97
            throw new Constants_1.BaileysError(`Unexpected error in login`, { response, status: response.status });
                  ^

BaileysError: Unexpected error in login
    at WAClient.authenticate (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40) {
  status: 419,
  context: { response: { status: 419 }, status: 419 }
}

**Comment by satyammayy** [comment]
@PrajjwalDatir @SomnathDas @AlenSaito1 @bilal-08

**Comment by satyammayy** [comment]
Anyone ?

**Comment by PrajjwalDatir** [comment]
- check if your mobile has good internet connection.
- try updating your baileys version to the latest.
- try Using new session id

let us know how it goes.

**Comment by AlenSaito1** [comment]
@satyammayy Gussing from the error, Looks like the session stored in the db is not valid anymore, This happens when you logout from WhatsApp Web from your phone. 

The solution is to change the `SESSION` in Config Vars

**Comment by satyammayy** [comment]
@ @PrajjwalDatir @AlenSaito1 
i will install void again try again

**Comment by satyammayy** [comment]
root@ghost-Presario-CQ43-Notebook-PC:/home/ghost/try/Whatsapp-Botto-Void# npm start

> whatsapp-botto-void@1.0.0 start
> node dist/void.js

[VOID] 22/09 05:24:09 Starting...
[VOID] 22/09 05:24:15 Loading Commands...
[VOID] 22/09 05:24:19 Loaded: ban from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Dev/Ban.js
[VOID] 22/09 05:24:20 Loaded: disable from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Dev/Disable.js
[VOID] 22/09 05:24:21 Loaded: enable from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Dev/Enable.js
[VOID] 22/09 05:24:23 Loaded: eval from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Dev/Eval.js
[VOID] 22/09 05:24:24 Loaded: unban from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Dev/Unban.js
[VOID] 22/09 06:24:09 Loaded: trigger from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Fun/Trigger.js
[VOID] 22/09 06:24:10 Loaded: admins from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Admins.js
[VOID] 22/09 06:24:11 Loaded: everyone from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Everyone.js
[VOID] 22/09 06:24:12 Loaded: help from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Help.js
[VOID] 22/09 06:24:13 Loaded: mods from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Mods.js
[VOID] 22/09 06:24:15 Loaded: profile from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Profile.js
[VOID] 22/09 06:24:16 Loaded: xp from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/General/Xp.js
[VOID] 22/09 06:58:06 Loaded: spotify from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/Spotify.js
[VOID] 22/09 06:58:08 Loaded: yta from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/YTAudio.js
[VOID] 22/09 06:58:10 Loaded: yts from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/YTSearch.js
[VOID] 22/09 06:58:11 Loaded: ytv from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Media/YTVideo.js
[VOID] 22/09 06:58:12 Loaded: delete from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Misc/Delete.js
[VOID] 22/09 06:58:13 Loaded: hi from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Misc/Hi.js
[VOID] 22/09 06:58:14 Loaded: void from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Misc/Void.js
[VOID] 22/09 06:58:16 Loaded: activate from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Moderation/Activate.js
[VOID] 22/09 06:58:17 Loaded: deactivate from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Moderation/Deactivate.js
[VOID] 22/09 06:58:18 Loaded: demote from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Moderation/Demote.js
[VOID] 22/09 06:58:20 Loaded: promote from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Moderation/Promote.js
[VOID] 22/09 06:58:21 Loaded: remove from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Moderation/Remove.js
[VOID] 22/09 06:58:23 Loaded: blur from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Utils/Blur.js
[VOID] 22/09 06:58:25 Loaded: sticker from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Utils/Sticker.js
[VOID] 22/09 06:58:29 Loaded: subred from /home/ghost/try/Whatsapp-Botto-Void/dist/commands/Utils/Subred.js
[VOID] 22/09 06:58:29 Successfully Loaded 27 Commands
[VOID] 22/09 06:58:30 Loading Assets...
[VOID] 22/09 06:58:48 Loaded: 404 from /home/ghost/try/Whatsapp-Botto-Void/assets/images/404.png
[VOID] 22/09 06:58:53 Loaded: spoiler from /home/ghost/try/Whatsapp-Botto-Void/assets/images/spoiler.jpg
[VOID] 22/09 06:58:54 Loaded: triggered from /home/ghost/try/Whatsapp-Botto-Void/assets/images/triggered.png
[VOID] 22/09 06:58:57 Loaded: void from /home/ghost/try/Whatsapp-Botto-Void/assets/images/void.png
[VOID] 22/09 06:58:58 Successfully Loaded 4 Assets
[VOID] 22/09 06:59:17 Server Started on PORT: 4040
[VOID] 22/09 07:50:36 Connected to Database!
/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97
            throw new Constants_1.BaileysError(`Unexpected error in login`, { response, status: response.status });
                  ^

BaileysError: Unexpected error in login
    at WAClient.authenticate (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/ghost/try/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40) {
  status: 419,
  context: { response: { status: 419 }, status: 419 }
}

**Comment by satyammayy** [comment]
Still didn't solve

**Comment by bilal-08** [comment]
> Still didn't solve

Come to Discord and Say the Problem briefly with SS

**Comment by AlenSaito1** [comment]
@satyammayy are you using the same `SESSION`?

**Comment by satyammayy** [comment]
@AlenSaito1   no It's new

QR code never showed up

**Comment by satyammayy** [comment]
@bilal-08   Discord Link ? I don't have it

**Comment by PrajjwalDatir** [comment]
> 
> 
> @AlenSaito1 no It's new
> 
> QR code never showed up

Did you change the `Session id` to something else?
here changing `session` doesn't mean a new instance of Void.
I hope that's not the issue.

Anyway -> 
## Let's Discord

**Comment by satyammayy** [comment]
@ i only
 changed those things in .env file

**Comment by satyammayy** [comment]
let me attach a video file

**Comment by satyammayy** [comment]
https://anonfiles.com/f9W1Qe2euc/bottoerror_mp4

**Comment by satyammayy** [comment]
On google cloud shell


Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
satyammay123@cloudshell:~$ git clone https://github.com/Synthesized-Infinity/Whatsapp-Botto-Void
fatal: destination path 'Whatsapp-Botto-Void' already exists and is not an empty directory.
satyammay123@cloudshell:~$ rm -rf
satyammay123@cloudshell:~$ rm -rf ^C
satyammay123@cloudshell:~$ Whatsapp-Botto-Void
-bash: Whatsapp-Botto-Void: command not found
satyammay123@cloudshell:~$ rm -rf Whatsapp-Botto-Void
satyammay123@cloudshell:~$ git clone https://github.com/Synthesized-Infinity/Whatsapp-Botto-Void
Cloning into 'Whatsapp-Botto-Void'...
remote: Enumerating objects: 1209, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 1209 (delta 170), reused 151 (delta 134), pack-reused 1009
Receiving objects: 100% (1209/1209), 1.02 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (737/737), done.
satyammay123@cloudshell:~$ cd Whatsapp-Botto-Void
satyammay123@cloudshell:~/Whatsapp-Botto-Void$ ls
app.json  assets  Features.md  LICENSE  package.json  package-lock.json  Procfile  public  README.md  src  tsconfig.json
satyammay123@cloudshell:~/Whatsapp-Botto-Void$ npm i && npm i -D

> whatsapp-botto-void@1.0.0 postinstall
> npm run build


> whatsapp-botto-void@1.0.0 build
> tsc -p .


added 657 packages, and audited 912 packages in 24s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> whatsapp-botto-void@1.0.0 postinstall
> npm run build


> whatsapp-botto-void@1.0.0 build
> tsc -p .


up to date, audited 912 packages in 11s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
satyammay123@cloudshell:~/Whatsapp-Botto-Void$ nano .env.example
satyammay123@cloudshell:~/Whatsapp-Botto-Void$
satyammay123@cloudshell:~/Whatsapp-Botto-Void$ npm start

> whatsapp-botto-void@1.0.0 start
> node dist/void.js

[VOID] 28/11 03:13:28 Starting...
[VOID] 28/11 03:13:35 Loading Commands...
[VOID] 28/11 03:13:38 Loaded: ban from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Dev/Ban.js
[VOID] 28/11 03:13:39 Loaded: disable from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Dev/Disable.js
[VOID] 28/11 03:13:39 Loaded: enable from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Dev/Enable.js
[VOID] 28/11 03:13:40 Loaded: eval from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Dev/Eval.js
[VOID] 28/11 03:13:41 Loaded: unban from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Dev/Unban.js
[VOID] 28/11 03:14:04 Loaded: chess from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Fun/Chess.js
[VOID] 28/11 03:16:38 Loaded: trigger from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Fun/Trigger.js
[VOID] 28/11 03:16:39 Loaded: admins from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Admins.js
[VOID] 28/11 03:16:39 Loaded: everyone from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Everyone.js
[VOID] 28/11 03:16:41 Loaded: help from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Help.js
[VOID] 28/11 03:16:41 Loaded: mods from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Mods.js
[VOID] 28/11 03:16:43 Loaded: profile from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Profile.js
[VOID] 28/11 03:16:43 Loaded: xp from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/General/Xp.js
[VOID] 28/11 03:18:52 Loaded: spotify from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Media/Spotify.js
[VOID] 28/11 03:18:53 Loaded: yta from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Media/YTAudio.js
[VOID] 28/11 03:18:54 Loaded: yts from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Media/YTSearch.js
[VOID] 28/11 03:18:55 Loaded: ytv from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Media/YTVideo.js
[VOID] 28/11 03:18:56 Loaded: delete from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Misc/Delete.js
[VOID] 28/11 03:18:57 Loaded: hi from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Misc/Hi.js
[VOID] 28/11 03:18:58 Loaded: void from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Misc/Void.js
[VOID] 28/11 03:18:58 Loaded: activate from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Moderation/Activate.js
[VOID] 28/11 03:18:59 Loaded: deactivate from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Moderation/Deactivate.js
[VOID] 28/11 03:19:00 Loaded: demote from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Moderation/Demote.js
[VOID] 28/11 03:19:01 Loaded: promote from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Moderation/Promote.js
[VOID] 28/11 03:19:02 Loaded: remove from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Moderation/Remove.js
[VOID] 28/11 03:19:02 Loaded: blur from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Utils/Blur.js
[VOID] 28/11 03:19:03 Loaded: sticker from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Utils/Sticker.js
[VOID] 28/11 03:19:05 Loaded: subred from /home/satyammay123/Whatsapp-Botto-Void/dist/commands/Utils/Subred.js
[VOID] 28/11 03:19:05 Successfully Loaded 28 Commands
[VOID] 28/11 03:19:05 Loading Assets...
[VOID] 28/11 03:19:06 Loaded: 404 from /home/satyammay123/Whatsapp-Botto-Void/assets/images/404.png
[VOID] 28/11 03:19:06 Loaded: chess-notation from /home/satyammay123/Whatsapp-Botto-Void/assets/images/chess-notation.png
[VOID] 28/11 03:19:06 Loaded: spoiler from /home/satyammay123/Whatsapp-Botto-Void/assets/images/spoiler.jpg
[VOID] 28/11 03:19:07 Loaded: triggered from /home/satyammay123/Whatsapp-Botto-Void/assets/images/triggered.png
[VOID] 28/11 03:19:07 Loaded: void from /home/satyammay123/Whatsapp-Botto-Void/assets/images/void.png
[VOID] 28/11 03:19:07 Loaded: chess-win from /home/satyammay123/Whatsapp-Botto-Void/assets/videos/chess-win.mp4
[VOID] 28/11 03:19:07 Successfully Loaded 6 Assets
[VOID] 28/11 03:19:16 Server Started on PORT: 4040
[VOID] 28/11 03:47:43 Connected to Database!
(node:832) UnhandledPromiseRejectionWarning: BaileysError: Unexpected error in login
    at WAClient.authenticate (/home/satyammay123/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async WebSocket.<anonymous> (/home/satyammay123/Whatsapp-Botto-Void/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40)
(node:832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bilal-08** [comment]
> @bilal-08 Discord Link ? ok i will hop in

https://discord.gg/Nzsb5weQFg

come here :)

**Comment by satyammayy** [comment]
@bilal-08  no one replied
