### ISSUE TITLE
Enhancement :  Addition of song command !

### ISSUE THREAD

**Issue by satyammayy** [Synthesized-Infinity/Whatsapp-Botto-Void#30]
Can we use the first url from #yts command and download the song directly without gving #yta command !

@SomnathDas @PrajjwalDatir @AlenSaito1 @bilal-08

**Comment by NickoRey7** [comment]
U mean play cmd?

**Comment by PrajjwalDatir** [comment]
I'll try @AlenSaito1

**Comment by bilal-08** [comment]
> I'll try @AlenSaito1
> 📈 👾

>> can it play / download through yt music playlist which isn't available on yt 😬😬

**Comment by PrajjwalDatir** [comment]
@satyammayy @NickoRey7 @bilal-08 

# Here you go 🚀 🚀 🚀
