### ISSUE TITLE
BAN Command Improvement

### ISSUE THREAD

**Issue by Hiroto77** [Synthesized-Infinity/Whatsapp-Botto-Void#33]
If there are 2 Moderators. They Are able to ban each other. Lol. Request for fixing

**Comment by AlenSaito1** [comment]
Well

**Comment by Hiroto77** [comment]
> Well

Fixed :)???

**Comment by PrajjwalDatir** [comment]
@Hiroto77 Well for now...
Choose MODS whom you can trust.

**Comment by Hiroto77** [comment]
> @Hiroto77 Well for now...
> Choose MODS whom you can trust.

:) you mean... I, me and myself

**Comment by PrajjwalDatir** [comment]
> 
> 
> > @Hiroto77 Well for now...
> > Choose MODS whom you can trust.
> 
> :) you mean... I, me and myself

well!
if this fixed your problem, do close the issue.
