### ISSUE TITLE
Card game & meme cmd request!

### ISSUE THREAD

**Issue by NickoRey7** [Synthesized-Infinity/Whatsapp-Botto-Void#35]
So game is based on card like structure! The bot will send randomly a pic of characters eye in a card alike structure just like Pokémon game 
![dbkuocs-e75a1f76-a1ea-41da-b560-7bdbd1981484](https://user-images.githubusercontent.com/85819137/123512828-49255d00-d6a7-11eb-975c-e7745c3a83ca.jpg)
Take this above pic as an example. So if u wanna claim "prefix" claim chara name
Thats all the concept!

2nd one meme cmd.
Actually am not sure about this i found one api for this cmd "meme" which seems pretty intresting 
Link: https://github.com/AnimuAPI/Animu
Add if its good thats all!

**Comment by AlenSaito1** [comment]
@shubham8550 @SomnathDas @PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
@NickoRey7 

>2nd one meme cmd.
Actually am not sure about this i found one api for this cmd "meme" which seems pretty intresting
Link: AnimuAPI/Animu
Add if its good thats all!

actually **good meme** is subjective, and we can never have memebot which can deliver best memes.
so your `meme` command can be achieved by using `subred` with your favourite subreddit.

>So game is based on card like structure! The bot will send randomly a pic of characters eye in a card alike structure just like Pokémon game

It's good, see if you can come up with more interesting game ideas than just acquiring characters,then I'll be happy to give it a try
