### ISSUE TITLE
Cmd request!

### ISSUE THREAD

**Issue by NickoRey7** [Synthesized-Infinity/Whatsapp-Botto-Void#51]
1.bgsticker
=>Removes bg ( transparent) of gifs and convert to sticker without bg!

2.go-i
=> Usage> go-i kirito | 12
_will give you 12 images of kirito from google /pinterest/any other etc:
(Only reccomendation)

3.rename well | well
=> Will give you sticker with name well • well
(This is a selfish request tbh👀, so developers do only if interested)

Thanks,

**Comment by Hiroto77** [comment]
> 1.bgsticker
> =>Removes bg ( transparent) of gifs and convert to sticker without bg!
> 
> 2.go-i
> => Usage> go-i kirito | 12
> _will give you 12 images of kirito from google /pinterest/any other etc:
> (Only reccomendation)
> 
> 3.rename well | well
> => Will give you sticker with name well • well
> (This is a selfish request tbh, so developers do only if interested)
> 
> Thanks,

The 3rd one you requested is already in it . Usage => {prefix}sticker|void|Void
