### ISSUE TITLE
whatsapp multi device sign in support

### ISSUE THREAD

**Issue by Princevikas** [Synthesized-Infinity/Whatsapp-Botto-Void#61]
the bot works fine with old method, but if i try to sign in with multidevice sign in it just doesn't do anything

**Comment by AlenSaito1** [comment]
Blocked by https://github.com/adiwajshing/Baileys/pull/696

**Comment by AlenSaito1** [comment]
https://github.com/Synthesized-Infinity/Whatsapp-Botto-Entropy
