### ISSUE TITLE
QR code error

### ISSUE THREAD

**Issue by Doruk-Ayisor01** [Synthesized-Infinity/Whatsapp-Botto-Void#64]
I could deploy the app in heroku but the QR code isn't showing up.

**Comment by Doruk-Ayisor01** [comment]
@AlenSaito1 @SomnathDas @PrajjwalDatir @Nisarga-Developer

**Comment by Nisarga-Developer** [comment]
Show logs or the error message you see when you open the deployed app link

**Comment by 123Nihar321** [comment]
![qr](https://user-images.githubusercontent.com/87001468/148796620-34ed0e2d-c070-4462-9b9b-4ae166fc90b7.png)
this qr code can't open with whatsapp

**Comment by Nisarga-Developer** [comment]
> > Show logs or the error message you see when you open the deployed app link
> 
> {"message":"QR is not generated yet"} This message shows of after I authenticate...

Try reloading or redeploying the app with a fresh MongoDB URI

**Comment by Doruk-Ayisor01** [comment]
> > > Show logs or the error message you see when you open the deployed app link
> > 
> > 
> > {"message":"QR is not generated yet"} This message shows of after I authenticate...
> 
> Try reloading or redeploying the app with a fresh MongoDB URI

Auhh tried 4times💔

**Comment by ghost** [comment]
I fetched the error........

Anyway..... Thanks for some help @Nisarga-Developer
